### ISSUE TITLE
p2p/dnsdisc client_test.go error

### ISSUE THREAD

**Issue by jed-wemade** [wemixarchive/go-wemix#79]
#### Info
branch: master
commit hash: cad51f5

#### Expected behaviour
```
=== RUN   TestIteratorRootRecheckOnFail
    testlog.go:44: TRACE[05-21|11:18:54.054] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.054] DNS discovery lookup                     name=FDXN3SN67NA5DKA4J2GOK7BVQI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.054] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.054] DNS discovery lookup                     name=UYB465BIWP6Y2A4IHZXOXOWYZY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.054] DNS discovery lookup                     name=TFNWFLUENEZ4CRFT72DUFK2IMM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.054] DNS discovery lookup                     name=4CFBI4DDB4J6UW76AZFNIXAMKU.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.055] DNS discovery lookup                     name=LBPIF55NCD67KUHJUNBVOVUU5U.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.055] DNS discovery lookup                     name=GKQRIMZKHMR5B52NLSGC6P3OMY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.055] DNS discovery lookup                     name=J2OXBHGWJXZAIXPHSAD6646TBM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.055] DNS discovery lookup                     name=DMIEZBA6IT6F6HUC54HO7GSP3M.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.055] DNS discovery lookup                     name=JDXMLKAXD5CBBNVH76XYLKHGFM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.057] DNS discovery lookup                     name=DL5G3WLC7VWKLR6V3THI7MBMQA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.059] DNS discovery lookup                     name=3Q5O54QP4SGE5F6DF6ACKMTLSY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.061] DNS discovery lookup                     name=NUDST3E5E4DECY35PYAP3S3ADQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.063] DNS discovery lookup                     name=KCWBGLA74VWVNPZQRJLULFNW3Q.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.065] DNS discovery lookup                     name=YRPRUEKASO2FXNE4DFEHSHGQ4M.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.067] DNS discovery lookup                     name=G7M6M6GMY3VDHATE7QHHKIROME.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.069] DNS discovery lookup                     name=LB3TZDKYLF67ZFA6WEBQISJH64.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.071] DNS discovery lookup                     name=DO4Z6WEXXEONHDMJK6GMP6JR5A.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.073] DNS discovery lookup                     name=BP4AMU4DLA6RUYB5AXFU3K6ZKQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.075] DNS discovery lookup                     name=LHIJONZTPDB4M66EZHNI7UFRXA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.077] DNS discovery lookup                     name=LGWW46Y6T5ERFXTHHG4TYWM4MU.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.079] DNS discovery lookup                     name=476HX3YACXJGSPNKAKK2IDNTMY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.081] DNS discovery lookup                     name=HZR474NMJGBTACMQ752NOUGVB4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.083] DNS discovery lookup                     name=OPIUUMHCEIWM3VXBGBSQXQ4HGA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.084] DNS discovery lookup                     name=5WEJRW74DPNZMJZ7N3W224SOWI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.087] DNS discovery lookup                     name=7KXD6HGBZ4Z5JGPRVJVT6MUKB4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.089] DNS discovery lookup                     name=EJZAENYWHGFZH6SIKD4FC7DFEY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.091] DNS discovery lookup                     name=COJRZGASK7273YRULXYDAEXBEU.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.093] DNS discovery lookup                     name=OIBEYNVST7V2E6BMJNXCUVBQRE.n err=nil
    client_test.go:237: checkIterator called Next 25 times to find 25 nodes
    client_test.go:244: tree updated
    testlog.go:44: TRACE[05-21|11:18:54.098] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:54.098] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:54.098] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:54.098] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:54.098] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:54.098] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:54.101] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:54.101] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:54.103] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:54.103] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:54.105] DNS discovery lookup                     name=CBUYXZKRG6MT73NRQXZL25DBH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:54.105] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:54.105] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.107] DNS discovery lookup                     name=4WE4CJFMJS6K2IQJPZS23D4EN4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.109] DNS discovery lookup                     name=CD5FFFKUDIJHJ4W2Z327CWOKAQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.111] DNS discovery lookup                     name=LHIJONZTPDB4M66EZHNI7UFRXA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.113] DNS discovery lookup                     name=OIBEYNVST7V2E6BMJNXCUVBQRE.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.115] DNS discovery lookup                     name=WP3ZIJR5P4Z4BOYDTAAKG2ITCI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.117] DNS discovery lookup                     name=NLPWBFVW3HSP4HTLQY6GKURHMM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.119] DNS discovery lookup                     name=335QFH3VAAHGY6ACLI2MMLEUWA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.121] DNS discovery lookup                     name=RZ36LDPYU7VGW6YAI467LXLJ64.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.123] DNS discovery lookup                     name=K4WQSMAPBQJBB43D7PXLZKKX2I.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.125] DNS discovery lookup                     name=EXXSNLXFHC35ADCCGBPTJ7DCSY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.127] DNS discovery lookup                     name=LSNGAFFEHEEDSOEYVX65DHH32U.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.129] DNS discovery lookup                     name=476HX3YACXJGSPNKAKK2IDNTMY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.131] DNS discovery lookup                     name=YRPRUEKASO2FXNE4DFEHSHGQ4M.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.133] DNS discovery lookup                     name=BP4AMU4DLA6RUYB5AXFU3K6ZKQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.135] DNS discovery lookup                     name=7KXD6HGBZ4Z5JGPRVJVT6MUKB4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.137] DNS discovery lookup                     name=5WEJRW74DPNZMJZ7N3W224SOWI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.139] DNS discovery lookup                     name=AG53SCXXPUCWWERMF5SA5SUJ3E.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.141] DNS discovery lookup                     name=QVJFEHLI2LO5OEL55KXN7AOW6Q.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.143] DNS discovery lookup                     name=7AMKW4O5CH2ZMXIT765NBTSEJQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.145] DNS discovery lookup                     name=RTMQ7V5JDEFPNUXS4SUP4YMKTE.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.147] DNS discovery lookup                     name=WDAGU5YXV6CEPMOFKNEWSGLNZY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.149] DNS discovery lookup                     name=24G5B2ATKPSDDVAGTRH5ALYVS4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.151] DNS discovery lookup                     name=ROHVLTKFXATSRSOSCXKJILTQ2I.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.153] DNS discovery lookup                     name=W3AGKFY6QK4CAETGOM2JR7HFX4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.155] DNS discovery lookup                     name=YF4LZJRS36J4N63R5IISUUZX6U.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.157] DNS discovery lookup                     name=NUDST3E5E4DECY35PYAP3S3ADQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.159] DNS discovery lookup                     name=ZONUZWQD74B766BEH2VY2QDGXU.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.161] DNS discovery lookup                     name=LBPIF55NCD67KUHJUNBVOVUU5U.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.163] DNS discovery lookup                     name=G46PS2BHND6ZYGRFKUCCV6KYKE.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.165] DNS discovery lookup                     name=S4H4D2I5WH5JGMRQBUJVZIO3WU.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.167] DNS discovery lookup                     name=NMEFRDNOSY4MHLYXR5L5NDNNQM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.169] DNS discovery lookup                     name=TR4GTPTAVDPIUSYNH77CH7HUJI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.171] DNS discovery lookup                     name=TFNWFLUENEZ4CRFT72DUFK2IMM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:54.173] DNS discovery lookup                     name=PW7UTJYZMRR5YBFDWN3BV65T2A.n err=nil
    client_test.go:246: checkIterator called Next 30 times to find 30 nodes
--- PASS: TestIteratorRootRecheckOnFail (0.13s)
PASS
ok  	github.com/ethereum/go-ethereum/p2p/dnsdisc	0.162s
```

#### Actual behaviour
```
=== RUN   TestIteratorRootRecheckOnFail
    testlog.go:44: TRACE[05-21|11:18:20.079] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=FDXN3SN67NA5DKA4J2GOK7BVQI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=RGSO6DQP2ZPFH4H3TZLAADGQK4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=A74GF6XSF4QTEUTGXXU6NNX6EY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=E5MJH33U4RSUTGOWISGNU2I5YE.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=5FWUFSWHPHPH7YYKKMO4OPLE2U.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=YTGBMVFJKXWTLP6O6DRKB52QUQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.079] DNS discovery lookup                     name=YXDNRF6SGEL3W2DCWKNV2ORNGQ.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.080] DNS discovery lookup                     name=5XCMKDWLCGSXWILVVHIWWVOZQM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.080] DNS discovery lookup                     name=KAU43HJAS3RAPZTZJYKNXB6VVE.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.081] DNS discovery lookup                     name=EOS5JAONXO2XXPGEHXFOYIBMS4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.083] DNS discovery lookup                     name=JHY6LJQQW5C7EXGC6D3K4UHFMY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.085] DNS discovery lookup                     name=4LLSY5RC6EBQPQSYSXRFEF5EPA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.087] DNS discovery lookup                     name=7OYAZAGD7EURCLDRIUDXKS6HY4.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.089] DNS discovery lookup                     name=HW5D66SSTU5YVKLAF6P3RSZLZY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.091] DNS discovery lookup                     name=ZRUF7SYT2BIIHDZ76H3IKWSMXM.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.093] DNS discovery lookup                     name=XARTNMUW4O3AZTCGBNGRNCWZVA.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.095] DNS discovery lookup                     name=KVNFMBSLWRMHTUMM6JZ5OKUF2A.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.097] DNS discovery lookup                     name=T7BDNHH6NIADNM67N3I35HRJKI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.099] DNS discovery lookup                     name=M6FPE5KB2KKDNH4E5Q7IN3R2KY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.101] DNS discovery lookup                     name=EYOJYS7RESCWZ55OVCXFIHSAFY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.103] DNS discovery lookup                     name=F6PQUUYKDVUAY5YEFCEZ75JBCI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.105] DNS discovery lookup                     name=QCQTG7MCHX3PC2FX3CL7XA5J6Q.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.107] DNS discovery lookup                     name=7DWNHB2KUPKDKZKQ6QGQQIAPDU.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.109] DNS discovery lookup                     name=BZW6TQEM3PI2PGS55A5V5HWPCY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.111] DNS discovery lookup                     name=IEHHMYN7RS4QQQYQ7VAJJBHHGY.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.113] DNS discovery lookup                     name=7UPLNAQUWS5WAD54PGSXZRMX5Q.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.115] DNS discovery lookup                     name=RY7KUQPIWGS4Z7RCX73XI66IYI.n err=nil
    testlog.go:44: TRACE[05-21|11:18:20.117] DNS discovery lookup                     name=RWFCTCOEXWI2XRIXDX2ZHC7CWU.n err=nil
    client_test.go:237: checkIterator called Next 25 times to find 25 nodes
    client_test.go:244: tree updated
    testlog.go:44: TRACE[05-21|11:18:20.121] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:20.121] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:20.121] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:20.121] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:20.123] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:20.123] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:20.125] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:20.125] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:20.127] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:20.127] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:20.129] DNS discovery lookup                     name=6NRF6F4SON6FMSZXCRHIH55EH4.n err="not found"
    testlog.go:44: DEBUG[05-21|11:18:20.129] Error in DNS random node sync            tree=n err="not found"
    testlog.go:44: TRACE[05-21|11:18:20.129] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: DEBUG[05-21|11:18:20.129] Error in DNS random node sync            tree=n err="invalid root entry: invalid base64 signature"
    testlog.go:44: TRACE[05-21|11:18:20.129] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: DEBUG[05-21|11:18:20.130] Error in DNS random node sync            tree=n err="invalid root entry: invalid base64 signature"
    testlog.go:44: TRACE[05-21|11:18:20.130] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: DEBUG[05-21|11:18:20.130] Error in DNS random node sync            tree=n err="invalid root entry: invalid base64 signature"
    testlog.go:44: TRACE[05-21|11:18:20.130] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: DEBUG[05-21|11:18:20.130] Error in DNS random node sync            tree=n err="invalid root entry: invalid base64 signature"
    testlog.go:44: TRACE[05-21|11:18:20.130] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: DEBUG[05-21|11:18:20.130] Error in DNS random node sync            tree=n err="invalid root entry: invalid base64 signature"
    testlog.go:44: TRACE[05-21|11:18:20.130] Updating DNS discovery root              tree=n err=nil
    testlog.go:44: DEBUG[05-21|11:18:20.130] Error in DNS random node sync            tree=n err="invalid root entry: invalid base64 signature"
```

#### Steps to reproduce the behaviour
The test shows non-deterministic behaviour. It either passes or not.
```
go test -v -count 1 -timeout 10s ./p2p/dnsdisc/ -run TestIteratorRootRecheckOnFail
```

#### Backtrace
```
panic: test timed out after 10s
running tests:
	TestIteratorRootRecheckOnFail (10s)

goroutine 5 [running]:
testing.(*M).startAlarm.func1()
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:2259 +0x320
created by time.goFunc
	/Users/wm-id002306/.version_managers/update-golang/go/src/time/sleep.go:176 +0x38

goroutine 1 [chan receive]:
testing.(*T).Run(0x1400014e000, {0x104d9c8db?, 0x229e16beb7239?}, 0x104e55108)
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:1649 +0x350
testing.runTests.func1(0x1400007d1a0?)
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:2054 +0x48
testing.tRunner(0x1400014e000, 0x14000133c28)
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:1595 +0xe8
testing.runTests(0x1400010a8c0?, {0x104f7ee20, 0xf, 0xf}, {0x40?, 0x104e39fe0?, 0x104f97020?})
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:2052 +0x3b4
testing.(*M).Run(0x1400010a8c0)
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:1925 +0x538
main.main()
	_testmain.go:75 +0x1a8

goroutine 4 [select]:
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).slowdownRootUpdate(0x140001d78e8?, {0x104e581e0, 0x140001907d0})
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/sync.go:219 +0xfc
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).updateRoot(0x1400017b0e0, {0x104e581e0, 0x140001907d0})
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/sync.go:166 +0x3c
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncRandom(0x1400017b0e0, {0x104e581e0, 0x140001907d0})
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/sync.go:72 +0x50
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).nextNode(0x1400012c380)
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/client.go:282 +0x40
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).Next(0x1400012c380)
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/client.go:261 +0x20
github.com/ethereum/go-ethereum/p2p/dnsdisc.checkIterator(0x1400014e1a0, {0x104e57d10, 0x1400012c380}, {0x140001600f0, 0x1e, 0x0?})
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/client_test.go:370 +0x194
github.com/ethereum/go-ethereum/p2p/dnsdisc.TestIteratorRootRecheckOnFail(0x1400014e1a0)
	/Users/wm-id002306/github.com/wemixarchive/go-wemix/p2p/dnsdisc/client_test.go:246 +0x448
testing.tRunner(0x1400014e1a0, 0x104e55108)
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 1
	/Users/wm-id002306/.version_managers/update-golang/go/src/testing/testing.go:1648 +0x33c
FAIL	github.com/ethereum/go-ethereum/p2p/dnsdisc	10.039s
FAIL
```

**Comment by jed-wemade** [comment]
This issue comes from Go 1.20 or later. (related issue: https://github.com/ethereum/go-ethereum/pull/26690)
Please use Go 1.19 as specified in `go.mod`.
